// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7kJP-si4aFkrhyCyvASvImESyc_KGd4w',
    appId: '1:664155397702:web:662d288cc9424b36333447',
    messagingSenderId: '664155397702',
    projectId: 'market-ed6d9',
    authDomain: 'market-ed6d9.firebaseapp.com',
    storageBucket: 'market-ed6d9.appspot.com',
    measurementId: 'G-CZGPMWW3HC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQLFystCBc6qjIr2LzSWI2qdZsidUiKOc',
    appId: '1:664155397702:android:a123f4e605d7f860333447',
    messagingSenderId: '664155397702',
    projectId: 'market-ed6d9',
    storageBucket: 'market-ed6d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9qMyljvJaI9vR-Ash4VvwzpTqnopf5hQ',
    appId: '1:664155397702:ios:98bc29cdbf48eebf333447',
    messagingSenderId: '664155397702',
    projectId: 'market-ed6d9',
    storageBucket: 'market-ed6d9.appspot.com',
    iosBundleId: 'com.market.market',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9qMyljvJaI9vR-Ash4VvwzpTqnopf5hQ',
    appId: '1:664155397702:ios:98bc29cdbf48eebf333447',
    messagingSenderId: '664155397702',
    projectId: 'market-ed6d9',
    storageBucket: 'market-ed6d9.appspot.com',
    iosBundleId: 'com.market.market',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7kJP-si4aFkrhyCyvASvImESyc_KGd4w',
    appId: '1:664155397702:web:ead91e43184c01e5333447',
    messagingSenderId: '664155397702',
    projectId: 'market-ed6d9',
    authDomain: 'market-ed6d9.firebaseapp.com',
    storageBucket: 'market-ed6d9.appspot.com',
    measurementId: 'G-16G4VDTBHB',
  );
}
